### ISSUE TITLE
Question: backend Design patterns

### ISSUE THREAD

**Issue by richcoresln** [JordyLangen/ken-po-tatakai#1]
First off, kudos, I think this repo contains an excellent example of how to architect applications.
I am wondering about your opinion on the suitability of such a design pattern for function apps. 
To give a bit more context, doesn't handling data access yourself remove some of the benefits bindings provides with function apps?
Are there more benefits to using such a pattern other than being able to put a different "frontend" on it (i.e replacing function apps with aspnet webapi)?

**Comment by JordyLangen** [comment]
First off, thanks 😄 

Just to note, they way I've implemented the functions related to `User` are things you would normally put in a (asp.net) webapi I guess. I don't believe functions were built to be used like this, although it is supported. I think the main usage for the http trigger is to start long running http calls.

But on the other hand, I was very interested in the azure functions authentiation feature and this was a nice way of explorings its functionalities and integration options.

I'm mostly doing this project to try out azure functions and cosmosdb, and plan on using the cosmosdb change feed feature to implement certain features, and as wel using azure signalr to built some kind of realtime functionalities. You could argue that I'm only going to need a minimal set of http calls, and that using azure functions for this works fine.

> To give a bit more context, doesn't handling data access yourself remove some of the benefits bindings provides with function apps?

I would've used the `CosmosDB` input binding to get my data for the `GetUser` function, but this seemed very cumbersome as parts of the query had to come from the claims. But you could always opt to build your own binding that would extend the `CosmosDB` binding.

> Are there more benefits to using such a pattern other than being able to put a different "frontend" on it (i.e replacing function apps with aspnet webapi)?

In this case the the functions in the `User` domain will be accessed by a client, and I want to have full control over the HTTP status codes and messages that are being reported back to the client. For example using the `CosmosDB` output binding would make it very hard to report a "bad request" back to the client.

I believe there are two main scenario's that you will handling: events triggered by a client and events triggered by another component (be it cosmos db, a queue, storage). In case of the client I'd always want full control of its responses. In case of other components I'd always use the bindings, but still keep my business within the domain.
